### ISSUE TITLE
Too many recent items

### ISSUE THREAD

**Issue by hotice** [thirschbuechler/ubuntu-recentquicklists#10]
For some applications that are used to work with many files (e.g. a text editor like Gedit), the quicklist becomes huge when using ubuntu-recentquicklists. An option to only display X recent items (with a default of something like 5) would be great.

**Comment by thirschbuechler** [comment]
Yeah,  you're right, that can be a pain, I'll do it sometime.

PS: Webupd8 rules

**Comment by thirschbuechler** [comment]
done.
https://github.com/thirschbuechler/ubuntu-recentquicklists/pull/11
