### ISSUE TITLE
Wrong app used to open some files

### ISSUE THREAD

**Issue by hotice** [thirschbuechler/ubuntu-recentquicklists#14]
The wrong application is used to open files in some cases. 

For instance, I have Gedit set to open text files. However, accessing a recent quicklist from Gedit results in LibreOffice being used to open that file. This also happens with Image Viewer (Eye of GNOME): accessing any images from its recent quicklist results in Firefox opening that file. I didn't test too many apps, and I assume it happens with others as well.

The best case would be to open the file using the app for which the quicklist was used. If that's not possible, the default app for that file type should be used.

**Comment by thirschbuechler** [comment]
Please see
https://github.com/thirschbuechler/ubuntu-recentquicklists/wiki/Compatibility-and-FAQ#my-file-gets-opened-by-the-wrong-program

But, I'll try to make it happen

**Comment by hotice** [comment]
Ah, I missed that, thanks for the link!

**Comment by thirschbuechler** [comment]
I seem to have solved issues #13  and #14 in [this](https://github.com/thirschbuechler/ubuntu-recentquicklists/tree/incr_readability) branch, please let me know whether this works for you!

**Comment by hotice** [comment]
Yes, it works, great work! One small issue I noticed though, is that no recent quicklists are displayed for Gedit, in either the Incr_readability branch or the main branch, and if I remember correctly, it used it used to have them.

**Comment by thirschbuechler** [comment]
niice.

Well, I'm afraid I have to link to the [wiki](https://github.com/thirschbuechler/ubuntu-recentquicklists/wiki/Compatibility-and-FAQ#ft2) again :P 
Had the same issue, I'd guess you'd had to play around with it as described there, as well as "manual adding".
[Screenshot of gedit quicklist](ubuntu-recentquicklists/urq screenie2.png)

**Comment by thirschbuechler** [comment]
For now, I'll close this issue, since it was [resolved in the branch merge](https://github.com/thirschbuechler/ubuntu-recentquicklists/pull/15).

However, in case something else goes wrong (or some other form of feedback) I'll be happy to hear from you again!

**Comment by hotice** [comment]
Thanks! All seems fine now. Also, I posted an article about it on WebUpd8: http://www.webupd8.org/2016/08/add-recently-accessed-files-as.html

**Comment by thirschbuechler** [comment]
Cool!
