### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by orschiro** [thirschbuechler/ubuntu-recentquicklists#21]
Dear @thirschbuechler, 

Thank you for your promising solution!

I found it via [this thread](http://askubuntu.com/questions/803869/is-there-an-indicator-to-quickly-access-recently-used-files/829405#829405).

I followed the instructions provided there but it doesn't run.

Any ideas?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18815443/d5a6fd34-8331-11e6-8146-b21b3a7092b3.png)

**Comment by thirschbuechler** [comment]
Hm, the output looks ok, did you look at the [FAQ](https://github.com/thirschbuechler/ubuntu-recentquicklists/wiki/Compatibility-&-FAQ) and the [logging file](https://github.com/thirschbuechler/ubuntu-recentquicklists/wiki/Configuration-&-Logging)?
A rightclick on libreoffice calc does not yield any recent files? Make sure to open, write and close a (dummy) xls/ots file? I'm on 16.04 x64, and 14.04, 14.10 (both x64) also worked for me

**Comment by thirschbuechler** [comment]
I've just written a [bug-report guide](https://github.com/thirschbuechler/ubuntu-recentquicklists/wiki/Bug-Reporting), please let me know if the issue persists, or if you've figured it out, and how

**Comment by orschiro** [comment]
Dear @thirschbuechler,

Thank you so much!

I think now I finally understand how it works. 

I assumed launching your application will create another extra icon in Unity launcher.

However, if I understand correctly now, then it just adds entries to existing icons, e.g. LibreOffice, correct?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18828817/db19c3ac-83d9-11e6-818c-b141857b67f2.png)

**Comment by thirschbuechler** [comment]
Hello,
yes that's right! I'm glad it worked out.

I will close this issue and update the askubuntu-answer, but if you should find any other parts of the program confusing you can still reply to the thread if you want and help me improve the documentation

Cheers, Thomas

**Comment by orschiro** [comment]
> you can still reply to the thread if you want and help me improve the documentation

Thank you for the invitation! I will get back to you if I have further ideas. :-)

Warmly,

-Robert
